pipeline {
  agent none
       parameters {
         choice choices: 'model-base-python3\nex-py3', name: 'MODELNAME'
    //            string(
    //       			name: 'CODE_REPO',
    //       			defaultValue: 'https://github.com/RoboInterativo/simple-back-front.git',
    //       			description: 'CODE_REPO'
		//             )
		//  string(
		// 	name: 'BRANCH',
		// 	defaultValue: 'main',
		// 	description: 'BRANCH'
		// )


    }
  stages {
    stage('SCM') {
      agent any
      steps {
        script {
            sh 'rm -rf app'
            sh 'rm -rf node-v*'
            sh 'echo $WORKSPACE'
            CODE_REPO = 'git@github.com:RoboInterativo/robo-docs.git'
            CREDS = "ssh-git"
            BRANCH = "main"
            checkout([$class: 'GitSCM', branches: [[name: BRANCH]],
                doGenerateSubmoduleConfigurations: false,
                extensions: [[$class: 'RelativeTargetDirectory',
                relativeTargetDir: 'app/']], gitTool: 'Default',
                submoduleCfg: [], userRemoteConfigs: [[credentialsId: CREDS,
                url: CODE_REPO]]])
            sh """
            echo WORKSPACE=$WORKSPACE
            ls app/
            wget https://nodejs.org/dist/v17.9.1/node-v17.9.1-linux-x64.tar.gz
            tar xzvf node-v17.9.1-linux-x64.tar.gz
            export PATH=$WORKSPACE/node-v17.9.1-linux-x64/bin:$PATH
            cd app/my-website2
            node --version
            npm install -f && npm run build
            ls build
            """
      }
    }
}
//     stage('build') {
//      agent {
//         docker {
//           image 'node:16.20.0'
//           args '-e HOME=$WORKSPACE'
//         }
//         }
//       steps {
//         sh 'echo $HOME'
//       }

//   }
}
post {
    success {
        println 'WELLDONE'
        //Сохранить артифакты
    }
  }
}
